# Keyboard / Input
setxkbmap -option compose:ralt # for alt keyboard with custom firmware
numlockx &
# setxkbmap dvorak -option compose:ralt -option caps:swapescape
# xmodmap ~/.Xmodmap # using setxkbmap options now

# Daemons
# TODO: this hasn't been working; is the env var not set, or something else?
#mpdscribble --conf "$XDG_CONFIG_HOME/mpdscribble.conf" &
mpdscribble --conf "/home/perickso/.config/mpdscribble.conf" &
#thunar --daemon &
#dropbox &
#xautolock -time 30 -corners -000 -detectsleep -locker "systemctl suspend" &

# Monitor settings
xrandr --dpi 120 # X defaults to 48 because of stupid TV
#xflux -l 43.081331 -g -89.375952 & # adjust color temperature at night
redshift &
xset -dpms && xset s off & # don't let the screens fall asleep

# set track and time in dwm status
while true; do
  CURRENT_TRACK=$(timeout 30 mpc current --wait || echo $CURRENT_TRACK)
  xsetroot -name "${CURRENT_TRACK:+$CURRENT_TRACK 📾 }$(date '+%A, %B %d %l:%M %P')"
done &

# auto-restarts dwm without losing windows
while true; do
    dwm >/dev/null 2>&1 # No error logging
done

